apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vea-k8s-namespace
  name: vea-k8s-local-path-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi