apiVersion: v1
kind: Secret
metadata:
  namespace: vea-k8s-namespace
  name: vea-k8s-secret
stringData:
  REDIS_PASSWORD: foobared
  REDIS_URL: redis://:REDIS_PASSWORD@vea-k8s-redis-service:6379
type: Opaque
