---
apiVersion: v1
kind: Service
metadata:
  namespace: vea-k8s-namespace
  name: vea-k8s-nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vea-k8s-namespace
  name: vea-k8s-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      volumes:
        - name: vea-k8s-local-path-volume-claim
          persistentVolumeClaim:
            claimName: vea-k8s-local-path-volume-claim
        - name: vea-k8s-nginx-log
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      containers:
        - name: nginx
          image: vea/nginx
          terminationMessagePolicy: "File"
          terminationMessagePath: /dev/termination-log/
          imagePullPolicy: Never
          tty: true
          # volumeMounts:
          #   - name: vea-k8s-local-path-volume-claim
          #     mountPath: /usr/share/nginx/html/
          #   - name: vea-k8s-nginx-log
          #     mountPath: /var/log/nginx/
          ports:
            - containerPort: 80
              name: "http-server"
          resources:
            limits:
              memory: 512Mi
              cpu: 400m
            requests:
              memory: 256Mi
              cpu: 100m
status: {}
